### ISSUE TITLE
Suggestion: TMDB trending films and series (tvOS)

### ISSUE THREAD

**Issue by JeremTM93** [skrew/lillyplayer-support#10]
Integration of the weekly TMDB category "trendy" and/or "popular" and the ability to define its position on the homepage via the settings, "home view" section.

*Intégration de la catégorie hebdomadaire TMDB "tendance" et / ou "populaire" et de pouvoir définir sa position sur la page d'accueil via les paramètres, section "vue home".

**Comment by skrew** [comment]
I would prefer trakt.tv, as it's based on users uses, not on votes
