### ISSUE TITLE
Favourite films are not deleted immediately

### ISSUE THREAD

**Issue by JeremTM93** [skrew/lillyplayer-support#101]
Bug tvOS v3.0 :

When we delete a favourite film by long-clicking on the film tab, we have to wait for the application to restart before the change takes effect.

--

Lorsque nous supprimons un film en favoris à partir du clique long sur la jacquette de l'onglet films, nous devons attendre de redémarrer l'application pour prendre en compte le changement.

![1000006985.jpg](https://github.com/skrew/lillyplayer-support/assets/121438307/0104fcbf-b911-4f26-b4ce-923ba9dfdcc3)

**Comment by skrew** [comment]
3.0.3
