### ISSUE TITLE
No TV channel logos

### ISSUE THREAD

**Issue by JeremTM93** [skrew/lillyplayer-support#103]
Bug tvOS v3.0 :

The channel logos on the UIplayer after launching a replay from the replay section are missing.

--

Les logos de chaînes sur L'UIplayer après avoir lancer un replay à partir de la section replay sont absentes.

![1000006984.jpg](https://github.com/skrew/lillyplayer-support/assets/121438307/2587aa21-4e76-44c8-9b7f-729bfe192142)

**Comment by skrew** [comment]
3.0.3
