### ISSUE TITLE
Remove black band

### ISSUE THREAD

**Issue by JeremTM93** [skrew/lillyplayer-support#105]
Bug tvOS v3.0 :

A black band remains displayed on a movie or series view then in the player if :

 -We go to the Replay section
 -We start a replay, we pause it
 -We click on return to go to the settings then “edit a service”.

--

Une bande noire reste affichée sur une vue de film ou de série puis dans le lecteur si :

 -On va dans la section Replay
 -On démarre un replay, on le met en pause
 -On clique sur retour pour aller dans les paramètres puis "éditer un service".

![1000006987.jpg](https://github.com/skrew/lillyplayer-support/assets/121438307/9f647fc6-6be2-4c46-92c5-b4ab352d20fe)

![1000006989.jpg](https://github.com/skrew/lillyplayer-support/assets/121438307/62b0d251-7879-4399-af7f-9b790bea224f)

**Comment by skrew** [comment]
3.0.2
