### ISSUE TITLE
Informations trend home page

### ISSUE THREAD

**Issue by djokt** [skrew/lillyplayer-support#107]
Add an indication on the home page trends to show whether it's a film or a series.

Suggestion: either simply via text (film/series) or with logos like those on the navigation bar.
Also add the number of sources available.

*********

Ajouter une indication sur les tendances de la home page pour indiquer si il s'agit un film ou d'une série. 

Proposition : soit simplement via un texte (film/serie) soit avec des logos comme ceux de la barre de navigation
Ajouter aussi le nombre de sources disponibles.

**Comment by skrew** [comment]
3.0.4
