### ISSUE TITLE
Playlist sorting

### ISSUE THREAD

**Issue by HarveyJacobs** [skrew/lillyplayer-support#111]
Would be nice when on the edit content screen under edit playlist there was a few sort option 

alphabetical
By date added
Custom

**Comment by JeremTM93** [comment]
> Would be nice when on the edit content screen under edit playlist there was a few sort option 
> 
> alphabetical
> By date added
> Custom

https://github.com/skrew/lillyplayer-support/issues/90#issue-1984540653 ?

**Comment by skrew** [comment]
duplicate #90

**Comment by skrew** [comment]
Duplicate #90
