### ISSUE TITLE
WEBDAV content cannot be played

### ISSUE THREAD

**Issue by JeremTM93** [skrew/lillyplayer-support#112]
Bug tvOS v3.0 :

Our content added via the WEBDAV protocol cannot be read, regardless of the player used.

--

Nos contenus ajoutés via le protocole WEBDAV ne peuvent pas être lus, quel que soit le lecteur utilisé.

**Comment by skrew** [comment]
Webdav works, i'm using it daily. It's have been reported to not play with some services, like alldebrid. It's a FFmpeg / Web service problem, not a Lillyplayer problem.
