### ISSUE TITLE
Lilly player crashing frequently after recent app update

### ISSUE THREAD

**Issue by depunkar** [skrew/lillyplayer-support#113]
**Describe the bug**
The player is crashing frequently while watching contents or browsing. This happens frequently mostly during the first few minutes of opening the app when it is refreshing iptv playlist but I had also occured at other times. This used to happen in previous versions as well but is happening more frequently in version 3.30.

Platform - Apple tv, iPad.

**Comment by makey1900** [comment]
same here !

**Comment by skrew** [comment]
try with 3.0.1
