### ISSUE TITLE
Disable Dolby vision

### ISSUE THREAD

**Issue by frostychick** [skrew/lillyplayer-support#114]
Using the latest version on apple tv and couldnt disable dolby vision when the video is in dolby vision. I would like to view the content in hdr only. Is there any solution to this?

Thank you

**Comment by JeremTM93** [comment]
> Using the latest version on apple tv and couldnt disable dolby vision when the video is in dolby vision. I would like to view the content in hdr only. Is there any solution to this?
> 
> Thank you 

Yes, deactivate Dolby Vision on your television.
