### ISSUE TITLE
Home view order

### ISSUE THREAD

**Issue by HarveyJacobs** [skrew/lillyplayer-support#119]
It would be nice if the trends was added to the home view order screen so it could be moved down the list instead of just on or off

**Comment by makey1900** [comment]
ok with 3.01 !

**Comment by JeremTM93** [comment]
> ok with 3.01 !

I think @HarveyJacobs is talking about a category with all the trends from the series and films tabs, isn't that right?

**Comment by HarveyJacobs** [comment]
@JeremTM93 no the trends screen that shows up on the Home Screen when enabled it would be nice if you could move that down in the order so say I could put playlist above it

**Comment by skrew** [comment]
Not planned
