### ISSUE TITLE
no more subtitle with Mpvlib- 3.03 version !

### ISSUE THREAD

**Issue by makey1900** [skrew/lillyplayer-support#122]
version: 3.03
no more subtitle when Mpvlib player is select ( VOD )
 the same episode , when KSlib  or VLC is select , play normaly .

It wasn't lke this before  .

Try with a lot of different serie or movie, same result.

plus de sous titre quand Mpvlib est selectionné comme player pour les serie ou film..

**Comment by skrew** [comment]
3.0.4
