### ISSUE TITLE
MAC Stalker

### ISSUE THREAD

**Issue by VGer2072** [skrew/lillyplayer-support#128]
Sorry but i can't find a method to add a MAC Address to a new source.

Is this feature disappear ?
Would you please consider to re-enable it ?

**Comment by VGer2072** [comment]
It was so hard to get this info.
Is  "i want stalker back" in search view still works on last release ?

**Comment by skrew** [comment]
wait for the next version

**Comment by VGer2072** [comment]
Oh? Cool ! Thank you
