### ISSUE TITLE
Fix: live TV and VOD drop-down menu (tvOS)

### ISSUE THREAD

**Issue by JeremTM93** [skrew/lillyplayer-support#17]
After a first scroll through this drop-down menu, the App remembers the tab visited the first time instead of defaulting to "info" all the time.

*Après un premier déroulement de ce menu déroulant, l'App garde en mémoire l'onglet visité la première fois au lieu de tout le temps se remettre sur "info" par défaut.

**Comment by skrew** [comment]
This is not a bug but it is voluntary. BTW i understand it can be annoying.
Maybe resetting to "info" when you change the item playing would be a good compromise?

Ce n'est pas un bug, c'est volontaire. Par exemple, tu choisis une langue ou un sous-titre et tu veux en choisir une autre, c'est quand même plus pratique de revenir au même sous-menu.
Peut-être que réinitialiser la position à "info" quand tu changes de fichier serait un bon compromis ?

**Comment by JeremTM93** [comment]
I didn't think it was voluntary.
I understand that it keeps in memory for the current file, but when you change files you won't necessarily need the same tab as the last one opened.
However, it's original this way of working, it's up to us to put the position back on "information" indeed. You can close the ticket, I will adapt 😉


*Je ne pensais pas que c'était volontaire.
Je comprends que ça garde en mémoire pour le fichier en cours, mais quand tu changes de fichiers tu n'auras pas forcément besoin du même onglet que le dernier ouvert.
Cependant, c'est original ce fonctionnement, à nous de remettre la position sur "information" en effet. Tu peux clore le ticket, je m'adapterai 😉
