### ISSUE TITLE
Fix : improve the replay of the dropdown menu and the epg with KS (tvOS)

### ISSUE THREAD

**Issue by JeremTM93** [skrew/lillyplayer-support#25]
Replay from the drop-down menu or epg does not work or works poorly with KS.

*Le Replay du menu déroulant ou de l'epg ne fonctionne pas ou mal avec KS.

**Comment by JeremTM93** [comment]
MPVlib is also impacted... depending on the server as for KSlib.  The same program with another app works.

**Comment by skrew** [comment]
what is "not works or poorly works" ? it's an UI problem or it doesn't play ?

**Comment by JeremTM93** [comment]
Sometimes, with KS or MPV, the menu is displayed without the programmes, or only the next programmes.
With KS, you click on an old programme, it's ok but its EPG doesn't match. So you can't control the playback.

*Parfois, avec KS ou MPV, le menu s'affiche sans les programmes, ou seulement les prochains programmes.
Avec KS, tu cliques sur un ancien programme, c'est ok mais son EPG ne correspond pas. Donc impossible de contrôler la lecture.

**Comment by JeremTM93** [comment]
I have a problem with MPV:
when you start watching an old programme and bring up the timeline, the timeline has not progressed with the programme (it has stayed at the beginning of the program you selected).

*Je constate un problème avec MPV :
quand tu commences à regarder un ancien programme et que tu fais apparaître la ligne du temps, celle-ci n'a pas progressée avec le programme (elle est restée au début du programme que tu as sélectionné).

**Comment by skrew** [comment]
Check again in 3.0 and reopen ticket if it's still the case
