### ISSUE TITLE
Suggestion: automatic teaser / trailer in the background (tvOS)

### ISSUE THREAD

**Issue by JeremTM93** [skrew/lillyplayer-support#27]
On the page of a film or series, automatically play the teaser or trailer in the background when it is available.

*Sur la page d'un film ou d'une série, lire automatiquement en fond le teaser ou le trailer quand celui-ci est disponible.

**Comment by skrew** [comment]
Trop de trailers sont trop pourris pour que ca rende quelque chose de bien. J'avais essayé de le faire sur les tendances de la home, mais dans la moitié du temps le 1er trailer était quasiment les 5 premieres minutes du film, générique compris...
