### ISSUE TITLE
Fix: cache setting (tvOS)

### ISSUE THREAD

**Issue by JeremTM93** [skrew/lillyplayer-support#28]
When we change a value predefined by the application, it crashes.

*Lorsque nous changeons une valeur prédéfinie par l'application, celle-ci crash.

**Comment by skrew** [comment]
While using KS ?

**Comment by JeremTM93** [comment]
> While using KS ?

KS, exactly.

**Comment by skrew** [comment]
removed settings when not using MPV, as KSLib not have cache settings (yet ?)
