### ISSUE TITLE
App crashes when I try to change the size of subtitles 

### ISSUE THREAD

**Issue by cdguy** [skrew/lillyplayer-support#33]
I have the 1st gen AppleTV 4K.
When I use the VLC player, the app crashes when I try to change the size of the subtitles.
Also, the subtitles size do not change

![D6267D81-EC18-4B12-9A93-C873A16E63EE](https://user-images.githubusercontent.com/123307657/215282493-6e20e4de-17f4-45a4-b854-182a9662f125.jpeg)

**Comment by cdguy** [comment]
Same issue for the ios version of the app when using VLC lib on tvos

**Comment by skrew** [comment]
Removed settings when not using MPVLib, i have to handle this for VLCLib and KSLib
