### ISSUE TITLE
Added a "watch later" category

### ISSUE THREAD

**Issue by JeremTM93** [skrew/lillyplayer-support#35]
Add on each VOD page a "to watch later" button, to find these movies and series on the home page and in a category inside the corresponding tabs.
And be able to choose the position of this new category on the home page via the settings, "home view" section.

*Rajouter sur chaque page VOD un bouton "à regarder plus tard", pour retrouver ces films et séries sur la page d'accueil et dans une catégorie à l'intérieur des onglets correspondant.
Et pouvoir choisir la position de cette nouvelle catégorie sur la page d'accueil via les paramètres, section "vue home".

**Comment by skrew** [comment]
To me: Handle this with playlists like LillyPlayer iOS
