### ISSUE TITLE
Playlist To be watched later TVos

### ISSUE THREAD

**Issue by MatmanR14** [skrew/lillyplayer-support#37]
Have the possibility, as on ios, to create a section to watch later for VOD on the home page (TVOS).
With management to edit/delete via long left click for example.

*
Avoir la possibilité comme sur ios, de créer une section à regarder plus tard pour la VOD sur la page d’accueil (TVOS).
Avec la gestion pour modifier/supprimer via long clic gauche par exemple.

**Comment by skrew** [comment]
Duplicate #35
