### ISSUE TITLE
Series Poster metadata  can't get all sources on Apple Tv (Pro version)

### ISSUE THREAD

**Issue by Saidoua** [skrew/lillyplayer-support#38]
**To Reproduce**
Steps to reproduce the behaviour:
1. You have an iptv Source Add FTP  or Samba source
2. search for a title episode not existe on iptv  but existe on the other source
3. play this episode and stop, if you Lucky with the cache  you will find it in "Series in progresse"
4. in "Series in progresse" enter in this title poster try to play the same episode (not working), try to enter to episode description, scrolle down  to sources : error => second source not existe.

**Comment by skrew** [comment]
Can't reproduce, if you have another way to reproduce, reply here i will check it again.

What i have tested:

-> Searching for the serie "Black books", which is only available on my SMB share
-> Entering in the serie view from search
-> Click on "play" button
-> Stop the video after 3 seconds (long press on play / pause button to do a stop, not a pause)
-> Coming back to the home screen, Black books is listed in the first position of "Series in progress" as expected
-> Entering in the serie from the home
-> I can play (resume) the same episode directly from the play button
-> In the episode list, i can see my SMB source

**Comment by Saidoua** [comment]
its a bug my friend , Please see the photos,  tested with Tokyo Revengers :
![1](https://user-images.githubusercontent.com/54545861/216638875-b559c00a-700f-46a4-8447-be7b01680293.jpg)
![2](https://user-images.githubusercontent.com/54545861/216638879-6c678fa4-dc65-4873-a013-0af7887679a6.jpg)
![3](https://user-images.githubusercontent.com/54545861/216638881-4827d705-903e-4154-ac14-e0b20618bbbe.jpg)
![4](https://user-images.githubusercontent.com/54545861/216638885-3920d61b-037e-4e4f-ad0a-29e3871b6e9c.jpg)
![5](https://user-images.githubusercontent.com/54545861/216638888-2b096555-bf19-4656-8a7f-e53d224d56f9.jpg)

**Comment by skrew** [comment]
I think it's a problem with the matching, not a bug
On your second screenshot i can guess the problem. The filename looks horrible.

Try to rename your files in something like:

Tokyo.Revenger.S02E04.mkv

or something like that.

There are a lot of tools for renaming files on the web in a way to be clean and to avoid problems like yours.

**Comment by Saidoua** [comment]
OK tested i confirme it's not a bug, just need to rename files
