### ISSUE TITLE
Subtitles do not work

### ISSUE THREAD

**Issue by cdguy** [skrew/lillyplayer-support#42]
The subtitles do not work when using KSplayer still do not work with the latest update (04/02/2023) 
device used: iphone 11 pro max

**Comment by skrew** [comment]
It's better to report bugs on KS github directly, as i'm not the developer of this lib.
And, use the template and provide some infos (stream / link to reproduce, type of subtitles (text / image ... ?)

**Comment by cdguy** [comment]
For any kind of movies/series the subtitles can’t be displayed (they are not image based)

also I found a thread on ksplayer on how to list all subtitles:

https://github.com/kingslay/KSPlayer/issues/363

besides, I found 2 apps using KSplayer, and they do not have subtitle issues
