### ISSUE TITLE
spatial audio support

### ISSUE THREAD

**Issue by cdguy** [skrew/lillyplayer-support#45]
Is is known that ksplayer supports spatial audio, but apparently there is a bug.

I guess in order to send debug logs, spatial audio-compatible device should be used

can you help ksplayer to solve the issue?

https://github.com/kingslay/KSPlayer/issues/355

**Comment by skrew** [comment]
It's still bugged, so i'm waiting

**Comment by skrew** [comment]
available on 2.x
