### ISSUE TITLE
Exiting channel list

### ISSUE THREAD

**Issue by Tdlyman** [skrew/lillyplayer-support#47]
Not really a bug, just can’t figure out how to exit channel list when watching something.  Instead of scrolling all the way back to the channel you are watching and clicking it, is there a way to just exit the channel list to continue what you are currently watching?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS 16]
 - Player Lib: [e.g. MPVLib, KSLib...]

**Additional context**

**Comment by skrew** [comment]
Missing infos (at least the platform)

**Comment by Tomfr06** [comment]
If TVOS app, long press on play/pause.
