### ISSUE TITLE
I changed the AFR management in Lillyplayer and I let KS manage the AFR 100% by itself.

### ISSUE THREAD

**Issue by anrtiger** [skrew/lillyplayer-support#51]
I changed the AFR management in Lillyplayer and I let KS manage the AFR 100% by itself.
If it's still not good in the 2.6.2 version, re-open the ticket.

_Originally posted by @skrew in https://github.com/skrew/lillyplayer-support/issues/29#issuecomment-1404741832_

**Comment by anrtiger** [comment]
The AFR problem is still present with 2.6.2, the only solution, stop and restart. tvOS

**Comment by skrew** [comment]
I have opened #29 again
In the future use the template or write directly on the good ticket
