### ISSUE TITLE
bug with version 2.6.5

### ISSUE THREAD

**Issue by makey1900** [skrew/lillyplayer-support#52]
with last version 2.6.5 
-does not always synchronize playlists (between ipad and apple tv)
-no longer reads certain streams (even with vlc kit), whereas it did before the update
-does not display recently played movies correctly

-ne synchronise pas les playlists ( entre ipad et apple tv )
-ne lis plus certains flux ( meme avec vlc kit ), alors qu'il le faisait avant la mise à jour 
-n'affiche pas les films recemment joué correctement

**Comment by skrew** [comment]
Rien n'a changé concernant la synchronisation, la lib VLC ou l'affichage de la home. Merci d'utiliser le template, et de montrer des exemples reproductibles, car la ca ne sert pas à grand chose.
