### ISSUE TITLE
Replay not allowing to fast-forward

### ISSUE THREAD

**Issue by keleko86** [skrew/lillyplayer-support#53]
Hi all,

I assume that I am doing something wrong and I'd appreciate help or guidance.

When choosing a programme from the replay section, I can play the video and I can pause it. When paused, I am able to change the slider on the bottom from left to right, but the thing is that nothing happens then. I tried clicking the circle button (the "trackpad") and tried clicking play/pause and nothing happens. How can I make the video continue from the time chosen by the slider?

Thank you so much for your support in advance!

**Comment by skrew** [comment]
Maybe a stream problem, check again in the 3.0 (when it's available) and if you still have the problem, open this ticket again
