### ISSUE TITLE
Adding new "latest supplier additions" categories

### ISSUE THREAD

**Issue by JeremTM93** [skrew/lillyplayer-support#54]
Creation of two new categories on the homepage and on the film and series tabs:

The first for the latest films added by the suppliers.
The second for the latest series added by the suppliers, ensuring that each time a new episode is added, the series returns on the left.

Of course, these new categories can be enabled/disabled and their positions can be defined in the homepage settings.

*Création de deux nouvelles catégories sur la page d'accueil et sur les onglets films et séries :

La première pour les derniers films ajoutés par les fournisseurs.
La seconde pour les dernières séries ajoutées par les fournisseurs, en veillant à ce qu'à chaque fois qu'un nouvel épisode est ajouté, la série revienne sur la gauche.

Bien entendu, ces nouvelles catégories peuvent être activées/désactivées et qu'il soit possible de définir leurs positions dans les paramètres de la page d'accueil.

**Comment by skrew** [comment]
The way you describe series doesn't fit with the category name. If a series returns to first position when an episode is added, it no longer fits with the category name.
I'd say "latest episodes added" instead.


Le fonctionnement que tu décris pour les séries ne colle pas avec l’intitulé de la catégorie. Si une série revient en première position quand un épisode est ajouté, ca ne colle plus avec le nom de la catégorie.
Je dirais plutôt “derniers épisodes ajoutés"
