### ISSUE TITLE
Lots of dropped frames in UHD streams

### ISSUE THREAD

**Issue by edge261** [skrew/lillyplayer-support#59]
**Describe the bug**
After some seconds, the video starts to drop frames and in general makes the video stutter. Refreshing the channel does not solve it.

**To Reproduce**
1. Open a UHD with HDR channel
2. Wait for the missing frames.

**Expected behavior**
Fluid video.

**Smartphone (please complete the following information):**
 - Device: Apple TV 4K 2022
 - OS: tvOS 16.5 / 17b1-b2
 - Player Lib: MPVLib

**Comment by skrew** [comment]
Uses KSlib instead of MPVLib  if it's not better since 3.0
