### ISSUE TITLE
VOD on pause crash the app with KSPlayer. 

### ISSUE THREAD

**Issue by thdmlh** [skrew/lillyplayer-support#62]
**Describe the bug**
While watching VOD and pause for a while, then app totally crash (return to AppleTV home or even no hdmi signal on TV)
This is only while using KSPlayer. 

 - Device: AppleTV 4K lastest model with LAN (A2843 model 128GB)
 - OS: latest version 16.5
 - Player Lib: KSLib

**Comment by thdmlh** [comment]
Confirmed that’s solved with iOS 16.6

**Comment by skrew** [comment]
Confirmed by another user on the chat.

Thanks
