### ISSUE TITLE
LillyPlayer Pro still shows adds

### ISSUE THREAD

**Issue by DannyKeg** [skrew/lillyplayer-support#65]
I subscribed to LillyPlayer Pro (iOS), but but I’m still seeing the adds and the menu still shows the “Subscribe to …” message.

**Comment by skrew** [comment]
It's a long time i know, but do you have contacted the support ?

**Comment by DannyKeg** [comment]
Yes, I tried to contact them by email, but didn’t receive an answer

**Comment by skrew** [comment]
i have looked in the support, i only see 1 mail from you (with a reply) in january
Can you give me the date of the mail ?

**Comment by DannyKeg** [comment]
I sent a mail to support on 17 June 2023

**Comment by skrew** [comment]
You got a reply, as i can see on this screenshot

<img width="1099" alt="Screenshot 2023-11-09 at 18 36 02" src="https://github.com/skrew/lillyplayer-support/assets/738170/d5264efe-de07-4ba9-9cd8-f950e5a19d1e">

**Comment by DannyKeg** [comment]
Very strange, my mail doesn’t show any reply ? But I have tried the “restore purchase” and nothing happens ?

**Comment by skrew** [comment]
For the next version, i will see if i can display any error message to see what's happen with your account. All i can say is the in-app purchase is working, as i don't have any other report on this issue for a long time. Stay tuned

**Comment by DannyKeg** [comment]
OK thanks for getting in touch, I will look forward to the next version

**Comment by skrew** [comment]
Waiting for the 3.0 version
