### ISSUE TITLE
No EPG on tvOS

### ISSUE THREAD

**Issue by lpkyer** [skrew/lillyplayer-support#66]
**Describe the bug**
I added an xtream source that I usually use with tivimate. It connects and I get channels. Then I upgraded to pro in hopes that I would get EPG. Still No EPG after rebooting Apple TV.

**Expected behavior**
I expect to see an EPG to navigate my channels 

![image](https://github.com/skrew/lillyplayer-support/assets/12514118/357eda2d-4400-4b3d-af59-2c3fb61ea590)
![image](https://github.com/skrew/lillyplayer-support/assets/12514118/38768192-7ba5-4f37-96b8-371e4c71bcfb)

**Smartphone (please complete the following information):**
 - Apple TV 4K
 - OS: [e.g. iOS 16]
 - tvOS 16.6
 - Player Lib: [e.g. MPVLib, KSLib...]
 - Mpv

**Comment by skrew** [comment]
Quand vous êtes dans la liste des chaines (2ème capture) faites un double click sur le bouton play / pause pour afficher le menu de gauche et accéder à l'EPG

Inutile d'acheter la version pro pour activer quoi que ce soit, c'est clairement indiqué partout
