### ISSUE TITLE
Play next episode not popping up around the end of episode

### ISSUE THREAD

**Issue by depunkar** [skrew/lillyplayer-support#71]
**Describe the bug**
Play next episode not popping up around the end of episode. (ipad, iPhone, Apple TV)

**Expected behavior**
Around the end of current episode (ideally around 40 secs before episode end), an option to play next episode should have popped up.

**Comment by JeremTM93** [comment]
> **Describe the bug**
> Play next episode not popping up around the end of episode. (ipad, iPhone, Apple TV)
> 
> **Expected behavior**
> Around the end of current episode (ideally around 40 secs before episode end), an option to play next episode should have popped up.
> 
> 

To be tested, but an invitation to launch the next episode after playing 97% of the video would be ideal.

**Comment by skrew** [comment]
3.0.2
