### ISSUE TITLE
Playback glitching when fast forwarding or rewinding

### ISSUE THREAD

**Issue by depunkar** [skrew/lillyplayer-support#73]
**Describe the bug**
Playback of a VOD video from iptv is not working properly after rewinding or fast forwarding. Most of the time the video doesn't go to the rewinded playback time and jumps to random minutes. At times the video crashes and restarts again from the beginning. Experienced it on Apple TV.

**Comment by skrew** [comment]
Test with 3.0 and tell me if it's still not ok
