### ISSUE TITLE
Iptv playlist and curated media library erasing automatically almost every day

### ISSUE THREAD

**Issue by depunkar** [skrew/lillyplayer-support#74]
**Describe the bug**
On Apple TV, lilly player is automatically deleting the iptv playlist. I have lilly player on iPad as well and turned on iCloud sync which acts as a workaround to not having to enter the playlist info again. However, the media library (movies, series) matching are all deleted. Since this takes a while to scan, it is annoying to have the curated media library and watch histories scanned updated every day. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS 16]
 - Player Lib: [e.g. MPVLib, KSLib...]

**Additional context**

**Comment by makey1900** [comment]
I have the same problem between apple tv, iphone...even mac

**Comment by JeremTM93** [comment]
> **Describe the bug**
> On Apple TV, lilly player is automatically deleting the iptv playlist. I have lilly player on iPad as well and turned on iCloud sync which acts as a workaround to not having to enter the playlist info again. However, the media library (movies, series) matching are all deleted. Since this takes a while to scan, it is annoying to have the curated media library and watch histories scanned updated every day. 
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Smartphone (please complete the following information):**
>  - Device: [e.g. iPhone6]
>  - OS: [e.g. iOS 16]
>  - Player Lib: [e.g. MPVLib, KSLib...]
> 
> **Additional context**
> Add any other context about the problem here.
> 

It's a tvOS bug that I've managed to fix by resetting my AppleTV!
