### ISSUE TITLE
Uniform darkening of the upper information banner with that of the lower banner.

### ISSUE THREAD

**Issue by Hayastano** [skrew/lillyplayer-support#93]
[TvOS]

For the new live top banner (channel indication and progress), the level of darkening at the top of the screen should be adjusted to the same level as the bottom banner (indication + info + replay + sources).
The bottom banner is darkened to around 1/4 of the screen, allowing the live feed in the background to be seen clearly, while the top banner is darkened to around 1/2 of the screen, really darkening the live feed in the background.
Uniform darkening from top to bottom to improve visibility of the background image and enhance the user experience.

----------------------------------

En ce qui concerne le nouveau bandeau supérieur en direct (indication des chaînes et progression), le niveau d'assombrissement du haut de l'écran devrait être ajusté au même niveau que le bandeau inférieur (indication + info + replay + sources).
Le bandeau du bas est assombri à environ 1/4 de l'écran, ce qui permet de voir clairement le direct en arrière-plan, alors que le bandeau du haut est assombri à environ 1/2 de l’écran, ce qui assombrit vraiment le direct en arrière-plan.
Pouvoir uniformisé l'assombrissement du haut à celui du bas pour améliorer la visibilité de l'image d'arrière-plan et améliorer l'expérience de l'utilisateur.

**Comment by skrew** [comment]
3.0.1
